spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      username: admin
      password: localconnection0104
      host: localhost
      port: 27017
      database: milipat-local

    redis:
      host: localhost
      port: 6379
      password: localconnection0104

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: none

  datasource:
    username: root
    password: localconnection0104
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local?serverTimezone=UTC&characterEncoding=UTF-8
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      password: 1

logging:
  level:
    org.hibernate.sql: debug

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    health:
      show-details: always
